eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9292/eureka/
  instance:
    hostname: localhost
    
microservice:
  department-service:
    endpoints:
      endpoint:
        uri: http://DEPARTMENT-SERVICE/departments/
  user-service:
    endpoints:
      endpoint:
        uri: http://USER-SERVICE/orders/    
